import { Button } from '~/components/ui/button';
import { Footer } from '~/components/ui/footer';

// TODO - Add icons for each of the lists in the features

function Header() {
  return (
    <div className="flex w-full flex-col items-start justify-start gap-20 bg-black/50 px-16 py-28">
      <div className="flex flex-col items-start justify-start gap-6">
        <div className="flex flex-col items-start justify-start gap-4 self-stretch">
          <div className="alternate normal text-base font-semibold">
            Optimize
          </div>
          <div className="flex flex-col items-start justify-start gap-6 self-stretch">
            <div className="alternate self-stretch text-[56px] font-bold">
              Maximize Your Success
            </div>
            <div className="alternate self-stretch text-lg font-normal">
              Explore our services and enhance your job search experience with
              WannabeEmployed.ai.
            </div>
          </div>
        </div>
        <div className="flex items-start justify-start gap-4 pt-4">
          <a href="/services">
            <Button>Learn More</Button>
          </a>
          <a href="/services">
            <Button className="bg-secondary">Sign Up</Button>
          </a>
        </div>
      </div>
    </div>
  );
}

function FeatureOne() {
  return (
    <div className="bg-Background flex flex-col items-start justify-start gap-20 px-16 py-28">
      <div className="flex items-center justify-start gap-20 self-stretch">
        <div className="flex shrink grow basis-0 flex-col items-start justify-start gap-8">
          <div className="flex flex-col items-start justify-start gap-6 self-stretch">
            <div className="self-stretch text-[40px] font-bold">
              Optimize Your LinkedIn Profile with AI-Generated Headlines and
              &amp;quot;About Me&amp;quot; Sections
            </div>
            <div className="self-stretch text-lg font-normal">
              Enhance your LinkedIn profile with compelling headlines and
              personalized &quot;About Me&quot; sections generated by our
              AI-powered job application assistant. Stand out to recruiters and
              increase your chances of getting noticed.
            </div>
          </div>
          <div className="flex flex-col items-start justify-start gap-4 self-stretch py-2">
            <div className="flex items-center justify-start gap-4 self-stretch">
              <div className="relative h-4 w-4" />
              <div className="normal shrink grow basis-0 text-base font-normal">
                Stand Out to Recruiters
              </div>
            </div>
            <div className="flex items-center justify-start gap-4 self-stretch">
              <div className="relative h-4 w-4" />
              <div className="normal shrink grow basis-0 text-base font-normal">
                Increase Your Chances of Getting Noticed
              </div>
            </div>
            <div className="flex items-center justify-start gap-4 self-stretch">
              <div className="relative h-4 w-4" />
              <div className="normal shrink grow basis-0 text-base font-normal">
                Optimize Your LinkedIn Profile
              </div>
            </div>
          </div>
        </div>
        <img
          className="shrink grow basis-0"
          src="https://via.placeholder.com/616x640"
          alt=""
        />
      </div>
    </div>
  );
}

function FeatureTwo() {
  return (
    <div className="bg-Background flex flex-col items-center justify-start gap-20 px-16 py-28">
      <div className="flex items-center justify-start gap-20 self-stretch">
        <img
          className="shrink grow basis-0"
          src="https://via.placeholder.com/616x640"
          alt=""
        />
        <div className="flex shrink grow basis-0 flex-col items-start justify-start gap-8">
          <div className="flex flex-col items-start justify-start gap-6 self-stretch">
            <div className="self-stretch text-[40px] font-bold">
              Create Professional Resumes and Cover Letters with Our AI-Powered
              Builder
            </div>
            <div className="self-stretch text-lg font-normal">
              Craft compelling resumes and cover letters effortlessly using our
              AI-driven builder. Tailor your applications to perfection and
              increase your chances of landing interviews.
            </div>
          </div>
          <div className="flex flex-col items-start justify-start gap-4 self-stretch">
            <div className="flex items-center justify-start gap-4 self-stretch">
              <div className="relative h-6 w-6" />
              <div className="normal shrink grow basis-0 text-base font-normal">
                AI-Driven Resume Builder
              </div>
            </div>
            <div className="flex items-center justify-start gap-4 self-stretch">
              <div className="relative h-6 w-6" />
              <div className="normal shrink grow basis-0 text-base font-normal">
                Tailor Applications with Ease
              </div>
            </div>
            <div className="flex items-center justify-start gap-4 self-stretch">
              <div className="relative h-6 w-6" />
              <div className="normal shrink grow basis-0 text-base font-normal">
                Increase Interview Opportunities
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function FeatureThree() {
  return (
    <div className="bg-Background flex flex-col items-start justify-start gap-20 px-16 py-28">
      <div className="flex items-center justify-start gap-20 self-stretch">
        <div className="flex shrink grow basis-0 flex-col items-start justify-start gap-6">
          <div className="relative h-12 w-12" />
          <div className="flex flex-col items-start justify-start gap-6 self-stretch">
            <div className="self-stretch text-[40px] font-bold">
              Stay Organized with Our Job Tracking Dashboard
            </div>
            <div className="self-stretch text-lg font-normal">
              Manage and monitor your job applications, follow-ups, and
              interview schedules in one place. Sign up now to streamline your
              job search process.
            </div>
          </div>
        </div>
        <img
          className="shrink grow basis-0"
          src="https://via.placeholder.com/616x640"
          alt=""
        />
      </div>
    </div>
  );
}

function CallToAction() {
  return (
    <div className="bg-Background flex flex-col items-start justify-start gap-20 px-16 py-28">
      <div className="flex flex-col items-start justify-start gap-6">
        <div className="flex flex-col items-start justify-start gap-6 self-stretch">
          <div className="self-stretch text-5xl font-bold">
            Transform Your Job Search Today
          </div>
          <div className="self-stretch text-lg font-normal">
            Discover the power of our AI-driven tools and land your dream job.
          </div>
        </div>
        <div className="flex items-start justify-start gap-4 pt-4">
          <a href="/services">
            <Button>Get Started</Button>
          </a>
          <a href="/services">
            <Button className="border-[1px] border-white bg-transparent">
              Learn More
            </Button>
          </a>
        </div>
      </div>
    </div>
  );
}

export default async function Services() {
  return (
    <div className="flex flex-col items-start justify-start">
      <Header />
      <FeatureOne />
      <FeatureTwo />
      <FeatureThree />
      <CallToAction />
      <Footer />
    </div>
  );
}
